engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


static_path_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
static_path = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('userauth.urls')),
    path('nominee/', include('nominee.urls')),
    path('sys/', include('voting.urls')),
    path('ioauth/', include('allauth.urls')),
] + static_path + static_path_media

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauth/urls.py
from django.urls import path
from .views import *


app_name = 'userauth'

urlpatterns = [
    path('', home, name='home'),
    path('login/', signin, name='login'),
    path('signup/', signup, name='signup'),
    path('verify-email/', email_verification, name='email_verification'),
    path('logout/', signout, name='logout'),
]

userauth/models.py
from datetime import timedelta
from django.utils import timezone
import random
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser):
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(unique=True)
    nickname = models.CharField(max_length=40, null=True)
    is_active = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class VertifyUser(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    is_expired = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.timenow = timezone.now()
            self.is_expired = self.timenow + timedelta(minutes=10)
        super().save(*args, **kwargs)

    def generate_code(self):
        code = str(
            random.randint(100000, 999999)
        )
        return code

userauth/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .validator import ValidatePassword
from .models import CustomUser


class UserSignUp(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    class Meta:
        model = CustomUser
        fields = ['last_name', 'first_name', 'nickname', 'email', 'password']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        validator = ValidatePassword()
        validator.validate(password)
        return password
    
    def save(self, commit=True):
        user = super(UserSignUp, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.is_active = False
            user.save()
        return user    
        

class passwordChangeForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput
        (
            attrs={'autocomplete': 'new-password'}
        ), 
            label="New Password"
    )
    confirmPassword = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password'}
        ), label="New Confirm Password"
    )
    class Meta:
        model = CustomUser
        fields = []

class LoginForm(AuthenticationForm):
    pass

userauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.mail import send_mail    
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.conf import settings
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .validator import activate_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.html import strip_tags
from .models import CustomUser, VertifyUser
from .forms import UserSignUp, LoginForm, UserSignUp, passwordChangeForm 
from django.utils import timezone
from django.contrib import messages


@csrf_protect
def home(request):
    user = CustomUser.objects.all()
    return render(request, '../templates/plate/home.html',{'user': user})  


@csrf_protect
def signup(request):
    if request.method == 'POST':
        form = UserSignUp(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            nickname = form.cleaned_data.get('nickname')
            password = form.cleaned_data.get('password')
            last_name = form.cleaned_data.get('last_name')
            first_name = form.cleaned_data.get('first_name')
            user = CustomUser(email=email, nickname=nickname, last_name=last_name, first_name=first_name)
            user.set_password(password)
            user.is_active = False 
            user.is_verified = False
            user.save()
            logout(request)
            verify_user = VertifyUser.objects.create(user=user)
            gen = verify_user.generate_code()
            verify_user.code = gen
            verify_user.save()
            current_site = get_current_site(request)
            message = render_to_string('../templates/userauth/account_activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'gen_code': gen,
            })
            message = strip_tags(message)
            mail_subject = 'Activate your account.'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [user.email]
            try:
                send_mail(mail_subject, message, email_from, recipient_list)
            except Exception as e:
                print(f'Email sending failed: {str(e)}')
            domain = current_site.domain
            messages.success(request, 'Please check your email to verify your account.')
            return render(request, 'userauth/checkemailmsg.html', {'domain': domain})
        else:
            return render(request, '../templates/userauth/signup.html', {'form': form})
    else:
        form = UserSignUp()
    return render(request, '../templates/userauth/signup.html', {'form': form})


@csrf_protect
def signin(request):
    form = LoginForm(data=request.POST)
    next_url = request.GET.get('next')
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            print(email, password)
            if user is not None:
                login(request, user)
                return redirect('voting:x6sad_dashboard')
            else:
                return render(request, '../templates/userauth/login.html', {'form': form, 'next': next_url, 'error': 'Invalid email or password'})
    return render(request, '../templates/userauth/login.html', {'form': form, 'next': next_url})


@require_http_methods(['POST'])
def signout(request):
    logout(request)
    return redirect('/')
     

@csrf_protect
def password_reset(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            try:
                user = CustomUser.objects.get(email=email)
                current_site = get_current_site(request)
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = default_token_generator.make_token(user)
                email_body = render_to_string('authentication_app/password_reset/password_reset_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': uid,
                    'token': token,
                    'protocol': 'http',
                    'site_name': '',
                })
                email_subject = 'Password reset on ' + current_site.domain
                email_body = strip_tags(email_body)
                try:
                    email = send_mail(email_subject, email_body, from_email=settings.EMAIL_HOST_USER, recipient_list=[user.email])
                    # email.send()
                    return render(request, 'authentication_app/password_reset/password_reset_done.html')
                except Exception as e:
                    return render(request, "{error message: address not found. " + str(e) + "}")
            except CustomUser.DoesNotExist:
                form.add_error(None, 'Email address not found, try again')
    else:
        form = PasswordResetForm()
    return render(request, 'authentication_app/password_reset/password_reset_form.html', {'form': form})


@csrf_protect
def resetPage(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirmPassword = request.POST['confirmPassword']
        newuser = User.objects.create_user( password = password, confirmPassword = confirmPassword)
        try:
            newuser.save()
        except ValueError:
            return HttpResponse('Please go back!') 
    else:
        form = LoginForm()
    return render(request, 'authentication_app/password_reset/password_reset_form.html')


@csrf_protect
def resetPageDone(request):
     return render(request, 'authentication_app/password_reset/password_reset_done.html')


@csrf_protect
def reset_password_confirm(request, uidb64, token):
    try:
        uid =force_str(urlsafe_base64_decode(uidb64))
        user = UserSignUp.objects.get(pf=uid)
    except(UserSignUp.DoesNotExist, TypeError, ValueError, OverflowError):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            form = passwordChangeForm(request.POST)
            if form.is_valid():
                new_password = form.cleaned_data.get('password')
                user.set_password(new_password)
                user.save()
                user =authenticate(request, email=user.email, password=new_password)
                login(request, user)
                
                return render(request, 'authentication_app/password_reset/password_reset_complete.html')
        else:
            form = passwordChangeForm()
        return render(request, 'authentication_app/password_reset/password_reset_confirm.html', {'form': form})
    else:
        return render(request, 'authentication_app/password_reset/404.html')
    

@csrf_protect
def email_verification(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        print(f"Code received: {code}")
        if not code:
            messages.error(request, 'Please enter the verification code.')
            return render(request, 'userauth/email_verification.html')
        try:
            verifyuser = VertifyUser.objects.get(code=code)
            print(f"verifyuser found: {verifyuser}")
        except VertifyUser.DoesNotExist:
            messages.error(request, 'Invalid verification code.')
            return render(request, 'userauth/email_verification.html')
        if timezone.now() > verifyuser.is_expired:
            messages.error(request, 'Verification code has expired.')
            return render(request, 'userauth/email_verification.html')
        user = verifyuser.user
        print(f"User found: {user}")
        if not user.is_active:
            user.is_active = True
            user.is_verified = True
            user.save()
            login(request, user, backend='userauth.backends.EmailBackend')
            messages.success(request, 'Your account has been successfully verified!')
            return redirect('voting:x6sad_dashboard')
        else:
            messages.info(request, 'Your account is already verified.')
            return redirect('voting:x6sad_dashboard')

    return render(request, 'userauth/email_verification.html')

templates/userauth/account_activation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
    <title>Email Verification</title>
</head>

<body>
    <div class="min-h-screen py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-2xl mx-auto">
            <div class="bg-white rounded-2xl shadow-xl overflow-hidden border">
                <div class="bg-gradient-to-r from-lime-green-600 to-lime-green-500 px-8 py-6">
                    <h1 class="text-2xl font-bold text-white">Email Verification</h1>
                </div>
                <div class="px-8 py-8 space-y-6">
                    <p class="text-gray-800">
                        Dear <span class="font-semibold text-lime-green-700">{{ user.first_name }}</span>,
                    </p>
                    <p class="text-gray-800">
                        Thank you for signing up! To complete your registration, please use the following verification code:
                    </p>
                    <div class="bg-lime-green-100 bg-opacity-50 backdrop-blur-sm border-2 border-lime-green-500 rounded-xl p-6 text-center shadow-md">
                        <p class="text-sm text-gray-700 mb-2 font-medium">Verification Code</p>
                        <p class="text-3xl font-bold text-lime-green-700 tracking-wider font-mono">
                            {{ gen_code }}
                        </p>
                    </div>
                    <p class="text-gray-800">
                        Alternatively, you can click on the link below to verify your account:
                    </p>
                    <div class="text-center">
                        <a href="http://{{ domain }}{% url 'userauth:email_verification' %}" 
                           class="inline-flex items-center justify-center px-8 py-3 bg-gradient-to-r from-lime-green-600 to-lime-green-500 text-white font-semibold rounded-lg shadow-lg hover:shadow-xl hover:from-lime-green-700 hover:to-lime-green-600 transition-all duration-200 transform hover:scale-105">
                            <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                            </svg>
                            Verify Account
                        </a>
                    </div>
                    <div class="bg-lime-green-50 border rounded-lg p-4">
                        <p class="text-xs text-gray-700 break-all">
                            <a href="http://{{ domain }}{% url 'userauth:email_verification' %}" 
                               class="text-lime-green-600 hover:text-lime-green-700 transition-colors duration-200">
                                http://{{ domain }}{% url 'userauth:email_verification' %}
                            </a>
                        </p>
                    </div>
                    <div class="bg-amber-50 border border-amber-200 rounded-lg p-4 mt-6">
                        <div class="flex items-start">
                            <svg class="w-5 h-5 text-amber-600 mr-3 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                            </svg>
                            <p class="text-sm text-amber-800">
                                If you did not request this, please ignore this email.
                            </p>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-gray-200">
                        <p class="text-gray-800">
                            Thank you!
                        </p>
                        <p class="text-gray-800 font-semibold text-lime-green-700 mt-2">
                            The Vault Team
                        </p>
                    </div>
                    <p class="text-xs text-gray-500 italic bg-gray-50 rounded-lg p-3 text-center">
                        This is an automated message, please do not reply.
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

templates/userauth/checkemailmsg.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Sent Successfully - Vault</title>
{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center px-4 py-12">
    <div class="max-w-2xl w-full">
        <div class="bg-white rounded-2xl overflow-hidden">
            <div class="bg-gradient-to-r from-lime-green-600 to-lime-green-500 px-8 py-6 text-center">
                <div class="inline-flex items-center justify-center w-16 h-16 bg-white rounded-full mb-4 shadow-lg">
                    <svg class="w-8 h-8 text-lime-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
                    </svg>
                </div>
                <h1 class="text-3xl font-bold text-white">Please Verify Your Email</h1>
            </div>
            <div class="px-8 py-8 space-y-6">
                <div class="bg-lime-green-50 border rounded-lg p-6">
                    <div class="flex items-start">
                        <svg class="w-6 h-6 text-lime-green-600 mr-3 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                        </svg>
                        <div>
                            <p class="text-gray-700 text-base leading-relaxed">
                                Thank you for signing up! To complete your registration, please check your email inbox and click the verification link we've sent to you.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="bg-amber-50 border border-amber-200 rounded-lg p-4">
                    <div class="flex items-start">
                        <svg class="w-5 h-5 text-amber-600 mr-3 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"/>
                        </svg>
                        <p class="text-amber-800 text-sm">
                            If you don't see the email in your inbox, please check your spam or junk mail folder.
                        </p>
                    </div>
                </div>
                <div class="pt-6 border-t border-gray-200">
                    <a href="{% url 'userauth:email_verification' %}" 
                       class="w-full inline-flex items-center justify-center px-8 py-3 bg-gradient-to-r from-lime-green-600 to-lime-green-500 text-white font-semibold rounded-lg shadow-lg hover:shadow-xl hover:from-lime-green-700 hover:to-lime-green-600 focus:outline-none focus:ring-4 focus:ring-lime-green-500 focus:ring-opacity-50 transition-all duration-200 transform hover:scale-105">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                        </svg>
                        Verify Email Now
                    </a>
                </div>
            </div>
            <div class="bg-lime-green-50 px-8 py-4 border-t border-lime-green-100 text-center">
                <p class="text-gray-700 text-sm">
                    Thanks,<br>
                    <span class="font-semibold text-lime-green-700">The Vault Team</span>
                </p>
            </div>
        </div>
        <div class="mt-6 text-center">
            <a href="{% url 'userauth:login' %}" class="text-lime-green-600 hover:text-lime-green-700 font-medium text-sm transition-colors duration-200">
                ← Back to Login
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/userauth/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Log In</title>
{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center px-4 py-12">
    <div class="max-w-md w-full">
        <div class="bg-lime-green-100 bg-opacity-30 rounded-2xl shadow-xl overflow-hidden backdrop-blur-sm">
            <div class="bg-lime-green-600 px-8 py-6 text-center">
                <div class="inline-flex items-center justify-center w-16 h-16 bg-lime-green-50 rounded-full mb-4 shadow-lg">
                    <svg class="w-8 h-8 text-lime-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
                    </svg>
                </div>
                <h2 class="text-2xl font-bold text-white">Log in to the Site</h2>
            </div>
            <div class="px-8 py-8">
                {% if form.errors %}
                    <div id="errorAlert" class="bg-red-50 border border-red-200 rounded-lg p-4 mb-6 transition-all duration-300">
                        <div class="flex items-start justify-between">
                            <div class="flex items-start flex-1">
                                <svg class="w-5 h-5 text-red-500 mr-3 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
                                </svg>
                                <p class="text-sm text-red-800">Your username and password didn't match. Please try again.</p>
                            </div>
                            <button onclick="dismissError()" class="ml-3 flex-shrink-0 text-red-500 hover:text-red-700 transition-colors">
                                <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                                </svg>
                            </button>
                        </div>
                    </div>
                {% endif %}
                <form method="post" class="space-y-6">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% for field in form %}
                        <div>
                            <label for="{{ field.id_for_label }}" class="block text-sm font-semibold text-gray-800 mb-2">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="text-lime-green-600">*</span>
                                {% endif %}
                            </label>
                            <input type="{{ field.field.widget.input_type|default:'text' }}" 
                                   name="{{ field.name }}" 
                                   id="{{ field.id_for_label }}"
                                   value="{{ field.value|default:'' }}"
                                   {% if field.field.required %}required{% endif %}
                                   class="w-full px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-lime-green-500 focus:border-transparent transition-all duration-200 bg-lime-green-50 border  "
                                   placeholder="{{ field.label }}">
                            {% if field.help_text %}
                                <p class="mt-2 text-sm text-gray-500">{{ field.help_text }}</p>
                            {% endif %}
                            {% if field.errors %}
                                <div class="field-error mt-2 text-sm text-red-600 transition-all duration-300">
                                    {% for error in field.errors %}
                                        <p class="flex items-center">
                                            <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"/>
                                            </svg>
                                            {{ error }}
                                        </p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="pt-2">
                        <button type="submit" 
                                class="w-full flex items-center justify-center px-8 py-3 bg-lime-green-600 text-white font-semibold rounded-lg shadow-lg hover:shadow-xl hover:bg-lime-green-700 focus:outline-none focus:ring-4 focus:ring-lime-green-500 focus:ring-opacity-50 transition-all duration-200 transform hover:scale-105">
                            <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"/>
                            </svg>
                            Log in
                        </button>
                    </div>
                </form>
                <div class="mt-6 text-center">
                    <p class="text-gray-800">
                        Don't have an account? 
                        <a href="{% url 'userauth:signup' %}" class="text-lime-green-600 hover:text-lime-green-700 font-semibold transition-colors duration-200">
                            Signup
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="mt-6 text-center text-sm text-gray-800">
            <p>By logging in, you agree to our <a href="#" class="text-lime-green-600 hover:text-lime-green-700 font-medium">Terms of Service</a> and <a href="#" class="text-lime-green-600 hover:text-lime-green-700 font-medium">Privacy Policy</a></p>
        </div>
    </div>
</div>

<style>
    @keyframes fadeOut {
        from {
            opacity: 1;
            transform: translateY(0);
        }
        to {
            opacity: 0;
            transform: translateY(-10px);
        }
    }
    .animate-fade-out {
        animation: fadeOut 0.3s ease-out forwards;
    }
</style>

<script>
    function dismissError() {
        const errorAlert = document.getElementById('errorAlert');
        if (errorAlert) {
            errorAlert.classList.add('animate-fade-out');
            setTimeout(() => {
                errorAlert.remove();
            }, 300);
        }
    }
    document.addEventListener('DOMContentLoaded', function() {
        const errorAlert = document.getElementById('errorAlert');
        const fieldErrors = document.querySelectorAll('.field-error');
        if (errorAlert) {
            setTimeout(function() {
                errorAlert.classList.add('animate-fade-out');
                setTimeout(() => {
                    errorAlert.remove();
                }, 300);
            }, 5000);
        }
        fieldErrors.forEach(function(fieldError) {
            setTimeout(function() {
                fieldError.classList.add('animate-fade-out');
                setTimeout(() => {
                    fieldError.remove();
                }, 300);
            }, 5000);
        });
    });
</script>
{% endblock %}